### ISSUE TITLE
PiHoleDNS in docker causing issues with DNS response times

### ISSUE THREAD

**Issue by Jack-Punter** [plaintextpackets/netprobe_lite#33]
I'm trying to use this tool, and also have a custom PiHole DNS server running on my local network in another docker container. My machines all access this dns server on the hosts IP (192.168.0.91) which is also the same machine I'm trying to run this on, however when I set that as my DNS server in `DNS_NAMESERVER_4_IP` I get a consistent timeout with a response from a docker IP (although interestingly not the IP that portainer lists as pihole's IP. Is there someway this setup can be supported, or something i can do to work around the issue (aside from simply not monitoring my pihole DNS server

```
The resolution lifetime expired after 5.138 seconds: Server Do53:192.168.0.91@53 answered got a response from ('172.21.0.1', 53) instead of ('192.168.0.91', 53); Server Do53:192.168.0.91@53 answered got a response from ('172.21.0.1', 53) instead of ('192.168.0.91', 53); Server Do53:192.168.0.91@53 answered got a response from ('172.21.0.1', 53) instead of ('192.168.0.91', 53); Server Do53:192.168.0.91@53 answered got a response from ('172.21.0.1', 53) instead of ('192.168.0.91', 53); Server Do53:192.168.0.91@53 answered got a response from ('172.21.0.1', 53) instead of ('192.168.0.91', 53); Server Do53:192.168.0.91@53 answered got a response from ('172.21.0.1', 53) instead of ('192.168.0.91', 53)
```

**Comment by securedpackets** [comment]
I’ll work on fixing this for Pinole users

**Comment by Jack-Punter** [comment]
Thanks for the quick reply! Other than this minor issue this has worked perfectly, thanks for your work on it. 👍

**Comment by plaintextpackets** [comment]
@Jack-Punter  can I get the version of Pihole you're running so I can test it myself

**Comment by Jack-Punter** [comment]
Hi I am currently on the following version of Pihole:
Docker Tag [2024.05.0](https://github.com/pi-hole/docker-pi-hole/releases/2024.05.0) Pi-hole [v5.18.2](https://github.com/pi-hole/pi-hole/releases/v5.18.2) FTL [v5.25.2](https://github.com/pi-hole/FTL/releases/v5.25.2) Web Interface [v5.21](https://github.com/pi-hole/AdminLTE/releases/v5.21)

and the service is defined in a docker compose "stack" in my portainer . the snippet is:
```
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: ${PIHOLE_WEB_PASSWORD}
    volumes:
      - pihole:/etc/pihole
      - './etc/dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
```

and the pihole volume is defined as an external volume at the bottom:
```
volumes:
  pihole:
    external: true
```
